import type { Metadata } from "next"
import { PublicPolicyPage } from "@/components/legal/public-policy-page"
import { LEGAL_EMAIL, LEGAL_EMAIL_HREF, SECURITY_EMAIL, SECURITY_EMAIL_HREF } from "@/lib/contact"

export const metadata: Metadata = { title: "Business Associate Agreement | SessionSteps" }

export default function BaaPage() {
  return <PublicPolicyPage eyebrow="HIPAA" title="Business Associate Agreement" description="The standard HIPAA Business Associate Agreement offered by SessionSteps LLC to eligible healthcare customers.">
    <section><h2>Important: acceptance</h2><p>This BAA becomes binding only when an authorized customer accepts it through SessionSteps&apos; contracting or account process, or both parties sign it. Publishing this page alone does not execute a BAA. “Covered Entity” means the accepting customer and “Business Associate” means SessionSteps LLC.</p></section>
    <section><h2>1. Definitions</h2><p>Capitalized terms not defined here have the meanings assigned by HIPAA, including the Privacy, Security, Breach Notification, and Enforcement Rules. “PHI” includes electronic PHI received, created, maintained, or transmitted by Business Associate for Covered Entity. “Services Agreement” means the Terms, order, or other agreement governing SessionSteps.</p></section>
    <section><h2>2. Permitted uses and disclosures</h2><p>Business Associate may use or disclose PHI only to perform the services, as permitted by this BAA, or as Required by Law. Business Associate may use PHI for proper management and administration or legal responsibilities only where HIPAA permits and appropriate assurances are obtained. Business Associate will not sell PHI, use it for advertising, or use it in a manner that would violate HIPAA if done by Covered Entity.</p></section>
    <section><h2>3. Safeguards</h2><p>Business Associate will implement appropriate administrative, physical, and technical safeguards and comply with applicable Security Rule requirements to protect the confidentiality, integrity, and availability of electronic PHI. Business Associate will mitigate harmful effects of an impermissible use or disclosure to the extent practicable.</p></section>
    <section><h2>4. Reporting</h2><p>Business Associate will report to Covered Entity any use or disclosure not permitted by this BAA, Security Incident, or Breach of Unsecured PHI of which it becomes aware, without unreasonable delay and no later than the time required by applicable law. Reports will include available information reasonably needed for Covered Entity&apos;s obligations. Routine unsuccessful security events that do not result in unauthorized access are reported in the aggregate unless a material event requires specific notice.</p></section>
    <section><h2>5. Subcontractors</h2><p>Business Associate will require subcontractors that create, receive, maintain, or transmit PHI on its behalf to agree to restrictions and safeguards at least as protective as those applicable to Business Associate. Current providers are described in the public Subprocessor List.</p></section>
    <section><h2>6. Individual rights and government access</h2><p>To the extent applicable to the services, Business Associate will make PHI available to Covered Entity for access, amendment, and accounting-of-disclosures obligations within a reasonable time; maintain information needed for those obligations; and make internal practices, books, and records relating to PHI available to the U.S. Department of Health and Human Services as required by law.</p></section>
    <section><h2>7. Covered Entity responsibilities</h2><p>Covered Entity will notify Business Associate of limitations in privacy notices, authorization changes, and agreed restrictions that affect use of PHI. Covered Entity will not ask Business Associate to use or disclose PHI in a way that would violate HIPAA if done by Covered Entity, and will configure access, users, integrations, and content appropriately.</p></section>
    <section><h2>8. Minimum necessary</h2><p>Each party will limit uses, disclosures, and requests for PHI to the minimum necessary as required by HIPAA and will use limited data sets where appropriate and practicable.</p></section>
    <section><h2>9. Term, termination, and return or destruction</h2><p>This BAA begins when validly accepted and remains in effect while Business Associate maintains PHI for Covered Entity. A material breach not cured within a reasonable period is grounds for termination. At termination, Business Associate will return or destroy PHI when feasible. If infeasible, it will extend this BAA&apos;s protections and limit further use or disclosure to the reason return or destruction is infeasible.</p></section>
    <section><h2>10. Interpretation and conflict</h2><p>This BAA will be interpreted to permit compliance with HIPAA. If it conflicts with the Services Agreement on PHI, this BAA controls. Regulatory references include later amendments. Obligations intended to survive termination will survive.</p></section>
    <section><h2>11. Contacts</h2><p>Legal and BAA questions: <a href={LEGAL_EMAIL_HREF}>{LEGAL_EMAIL}</a>. Security incident reports: <a href={SECURITY_EMAIL_HREF}>{SECURITY_EMAIL}</a>. Do not include PHI in unencrypted email.</p></section>
  </PublicPolicyPage>
}
