export type DemoWorksheet = {
  id: string
  title: string
  category: "CBT" | "DBT" | "ACT" | "Mindfulness" | "Relationships"
  description: string
  questions: string[]
}

export type IsolatedDemoClient = {
  id: string
  name: string
  initials: string
  type: "Individual" | "Teen" | "Couple"
  pronouns: string
  focus: string[]
  status: "Needs attention" | "Review requested" | "On track" | "New client"
  nextSession: string
  goals: string[]
  mood: number[]
  reflections: string[]
  assignments: { id: string; worksheetId: string; status: "Completed" | "In progress" | "Overdue"; due: string; response?: string }[]
  prep: { overview: string; progress: string; themes: string[]; questions: string[] }
}

// These mirror SessionSteps' evidence-informed worksheet categories and fields,
// but are deliberately plain objects: the public demo never reads production tables.
export const isolatedDemoWorksheets: DemoWorksheet[] = [
  { id: "thought-record", title: "Thought Record", category: "CBT", description: "Notice the connection between situations, thoughts, feelings, and responses.", questions: ["What happened?", "What automatic thought showed up?", "What evidence supports or challenges it?", "What is a more balanced thought?"] },
  { id: "behavioral-activation", title: "Behavioral Activation Planner", category: "CBT", description: "Plan small, meaningful activities and notice their effect on mood.", questions: ["What activity will you try?", "When will you do it?", "How difficult does it feel (1–10)?", "How did your mood change afterward?"] },
  { id: "values", title: "Values in Action", category: "ACT", description: "Clarify what matters and choose one values-aligned step.", questions: ["Which life area matters most right now?", "What value do you want to embody?", "What is one small action this week?", "What might get in the way?"] },
  { id: "grounding", title: "5–4–3–2–1 Grounding", category: "Mindfulness", description: "Reconnect with the present through the five senses.", questions: ["Name five things you can see.", "Name four things you can feel.", "Name three things you can hear.", "What changed after the exercise?"] },
  { id: "boundaries", title: "Healthy Boundaries", category: "DBT", description: "Prepare a clear, respectful boundary and plan how to communicate it.", questions: ["What situation needs a boundary?", "What do you need?", "How can you state it clearly?", "How will you care for yourself afterward?"] },
  { id: "repair", title: "Couples Repair Conversation", category: "Relationships", description: "Slow down conflict, understand impact, and make a repair attempt.", questions: ["What happened from each perspective?", "What feeling was underneath the reaction?", "What can each partner own?", "What repair would feel meaningful?"] },
  { id: "emotion-regulation", title: "Emotion Regulation Check-In", category: "DBT", description: "Name an emotion, its intensity, and an effective response.", questions: ["What emotion is present?", "How intense is it (1–10)?", "What urge comes with it?", "What response would serve you best?"] },
  { id: "self-compassion", title: "Self-Compassion Break", category: "Mindfulness", description: "Respond to a difficult moment with awareness and kindness.", questions: ["What feels difficult right now?", "How is this part of being human?", "What would you say to someone you care about?", "What do you need next?"] },
]

export const isolatedDemoClients: IsolatedDemoClient[] = [
  { id: "maya", name: "Maya Thompson", initials: "MT", type: "Individual", pronouns: "she/her", focus: ["Anxiety", "Work stress"], status: "Needs attention", nextSession: "Today · 11:30 AM", goals: ["Reduce workday rumination", "Practice grounding before difficult meetings"], mood: [7, 6, 6, 5, 4], reflections: ["Work pressure has made it harder to switch off at night.", "I used grounding before Monday's meeting and it helped."], assignments: [{ id: "maya-1", worksheetId: "values", status: "Completed", due: "Aug 31", response: "I want to act with steadiness, even when work feels urgent. I will leave my laptop closed during dinner." }, { id: "maya-2", worksheetId: "grounding", status: "In progress", due: "Sep 7" }], prep: { overview: "Maya's recent mood check-ins declined while work pressure increased.", progress: "Completed Values in Action and used grounding once before a meeting.", themes: ["Boundary-setting", "Evening rumination", "Workload"], questions: ["What changed as work pressure increased?", "Which boundary feels small enough to repeat?", "What made grounding useful on Monday?"] } },
  { id: "jordan", name: "Jordan Ellis", initials: "JE", type: "Individual", pronouns: "they/them", focus: ["Depression", "Activation"], status: "Review requested", nextSession: "Today · 2:00 PM", goals: ["Increase weekly activity", "Reconnect with supportive friends"], mood: [3, 4, 5, 5, 4], reflections: ["I took two walks but cancelled plans with Sam.", "Please bring this up next session: weekends feel especially flat."], assignments: [{ id: "jordan-1", worksheetId: "behavioral-activation", status: "Overdue", due: "Sep 1" }, { id: "jordan-2", worksheetId: "thought-record", status: "Completed", due: "Aug 26", response: "The thought was that reaching out would burden people. Sam's last message is evidence against that." }], prep: { overview: "Jordan flagged a weekend pattern for discussion and has one overdue activity plan.", progress: "Two walks completed; social reconnection remains difficult.", themes: ["Weekend withdrawal", "Fear of burdening others", "Small wins"], questions: ["What is different about weekends?", "What helped the two walks happen?", "Does the activity plan still feel like the right fit?"] } },
  { id: "sofia", name: "Sofia Ramirez", initials: "SR", type: "Individual", pronouns: "she/her", focus: ["Trauma", "Sleep"], status: "Needs attention", nextSession: "Tomorrow · 9:00 AM", goals: ["Build stabilization skills", "Improve sleep consistency"], mood: [6, 5, 4, 4, 3], reflections: ["Sleep was rough after a trigger at work."], assignments: [{ id: "sofia-1", worksheetId: "grounding", status: "Completed", due: "Sep 2", response: "I noticed the chair under me and named sounds in the room. My distress moved from 8 to 6." }], prep: { overview: "Sofia reports reduced sleep and a declining check-in pattern following a workplace trigger.", progress: "Used sensory grounding and reported a modest reduction in distress.", themes: ["Sleep disruption", "Workplace trigger", "Stabilization"], questions: ["What support is needed before exploring the trigger?", "Which grounding cue was easiest to access?", "What would make tonight feel safer?"] } },
  { id: "liam", name: "Liam Chen", initials: "LC", type: "Teen", pronouns: "he/him", focus: ["School anxiety", "Sleep"], status: "On track", nextSession: "Tomorrow · 3:30 PM", goals: ["Use coping skills before tests", "Reduce late-night worry"], mood: [5, 6, 5, 7, 6], reflections: ["Box breathing helped before the chemistry quiz."], assignments: [{ id: "liam-1", worksheetId: "thought-record", status: "In progress", due: "Sep 8" }], prep: { overview: "Liam is checking in consistently and reports one successful use of a coping skill.", progress: "Began a thought record and used breathing before a quiz.", themes: ["Test anxiety", "Skill confidence", "Sleep routine"], questions: ["What did you notice after breathing?", "Where did the thought record get difficult?", "What is one change to the bedtime routine?"] } },
  { id: "ava-noah", name: "Ava Patel & Noah Green", initials: "A+", type: "Couple", pronouns: "she/her & he/him", focus: ["Communication", "Conflict repair"], status: "Review requested", nextSession: "Friday · 10:00 AM", goals: ["Reduce escalation cycles", "Practice repair attempts"], mood: [7, 6, 6, 5, 5], reflections: ["We tried the repair script once. It lowered the tension, but we rushed the listening part."], assignments: [{ id: "couple-1", worksheetId: "repair", status: "Completed", due: "Sep 3", response: "Ava owned interrupting; Noah owned withdrawing. A ten-minute pause followed by reflecting back helped." }], prep: { overview: "The couple completed one repair attempt and identified listening as the fragile step.", progress: "Conflict intensity remains elevated, but both partners practiced ownership.", themes: ["Escalation", "Listening", "Repair attempts"], questions: ["What helped you return after the pause?", "When did listening begin to feel rushed?", "What repair could you repeat this week?"] } },
  { id: "ethan", name: "Ethan Brooks", initials: "EB", type: "Individual", pronouns: "he/him", focus: ["Burnout", "Irritability"], status: "On track", nextSession: "Monday · 9:00 AM", goals: ["Set work boundaries", "Improve recovery time"], mood: [6, 5, 4, 3, 4], reflections: ["I ended work on time twice and was more present at dinner."], assignments: [{ id: "ethan-1", worksheetId: "boundaries", status: "Completed", due: "Aug 30", response: "No email after 7 PM. I will tell my team in advance and silence notifications." }], prep: { overview: "Ethan reports early progress with end-of-day boundaries.", progress: "Stopped work on time twice and noticed improved connection at home.", themes: ["Over-responsibility", "Recovery", "Family connection"], questions: ["What made the boundary work twice?", "What happened on the other days?", "How did being present affect irritability?"] } },
  { id: "nia", name: "Nia Williams", initials: "NW", type: "Individual", pronouns: "she/her", focus: ["Grief", "Depression"], status: "On track", nextSession: "Tuesday · 1:00 PM", goals: ["Name grief triggers", "Restore morning routine"], mood: [4, 4, 5, 6, 5], reflections: ["Mornings are getting easier, but Sundays still catch me off guard."], assignments: [{ id: "nia-1", worksheetId: "self-compassion", status: "Completed", due: "Sep 2", response: "I can miss him and still let myself have an ordinary day." }], prep: { overview: "Nia's morning routine is improving, with Sundays remaining a predictable grief trigger.", progress: "Completed a self-compassion practice and reports less difficult mornings.", themes: ["Anniversary reactions", "Routine", "Permission for ordinary moments"], questions: ["What makes Sundays distinct?", "Which morning step is most reliable now?", "How did the compassionate statement land?"] } },
  { id: "oliver", name: "Oliver Bennett", initials: "OB", type: "Individual", pronouns: "he/him", focus: ["Relationships", "Trauma"], status: "New client", nextSession: "Wednesday · 4:00 PM", goals: ["Track shutdown cues", "Practice boundaries after conflict"], mood: [], reflections: [], assignments: [], prep: { overview: "Oliver is new to the practice; no between-session data is available yet.", progress: "Intake completed. Establish pacing and choose a first collaborative practice.", themes: ["Rapport", "Preferences", "Stabilization"], questions: ["What would make between-session work useful?", "How should we notice when pacing feels too fast?", "Which goal feels most important to begin with?"] } },
]

export const demoHistory = ["Aug 7 · Intake and goals", "Aug 14 · First worksheet assigned", "Aug 21 · Check-in reviewed", "Aug 28 · Progress and care plan updated"]
