import type { Metadata } from "next"
import { PublicPolicyPage } from "@/components/legal/public-policy-page"
export const metadata: Metadata = { title: "AI and Emergency Use Notice | SessionSteps" }
export default function AiEmergencyPage() { return <PublicPolicyPage eyebrow="Clinical safety" title="AI and Emergency Use Notice" description="Important limits for SessionSteps AI-assisted tools and between-session workflows.">
  <section><h2>Not an emergency service</h2><p>SessionSteps does not continuously monitor assignments, check-ins, messages, or client activity and cannot guarantee that a therapist will see information promptly. Do not use SessionSteps to request emergency help or report an immediate safety threat. In the United States, call 911 for an emergency or call or text 988 for the Suicide &amp; Crisis Lifeline. Outside the United States, contact the appropriate local emergency or crisis service.</p></section>
  <section><h2>AI output is a draft</h2><p>AI-assisted summaries, suggestions, and generated materials can be incomplete, inaccurate, biased, outdated, or unsuitable for a particular person. They are not a diagnosis, treatment recommendation, risk assessment, or substitute for review of the underlying record.</p></section>
  <section><h2>Required human review</h2><p>A qualified professional must review all AI output before using or sharing it. AI output must not be the sole basis for diagnosis, treatment, medication, safety planning, involuntary intervention, eligibility, or another consequential decision.</p></section>
  <section><h2>Customer responsibilities</h2><ul><li>Confirm facts against source information and the client&apos;s current circumstances.</li><li>Use independent clinical judgment and follow licensure, consent, documentation, and supervision obligations.</li><li>Tell clients how between-session tools are monitored and provide separate crisis instructions.</li><li>Use AI with PHI only where the customer&apos;s agreement, BAA, configuration, and law permit it.</li></ul></section>
  </PublicPolicyPage> }
