import type { Metadata } from "next"
import { PublicPolicyPage } from "@/components/legal/public-policy-page"
import { PRIVACY_EMAIL, PRIVACY_EMAIL_HREF } from "@/lib/contact"
export const metadata: Metadata = { title: "Data Retention and Deletion | SessionSteps" }
export default function DataRetentionPage() { return <PublicPolicyPage eyebrow="Privacy" title="Data Retention and Deletion Policy" description="How long SessionSteps keeps information and how authorized customers can request export or deletion.">
  <section><h2>Active accounts</h2><p>Account information and customer content are retained while the account is active and as needed to provide the service. Healthcare customers determine their clinical record-retention obligations and should establish their own retention and export procedures.</p></section>
  <section><h2>After cancellation or termination</h2><p>Authorized account owners should export needed information before access ends. We may maintain a limited recovery period described in the applicable order or account notice, after which customer content is deleted or de-identified from active systems unless law, a legal hold, dispute, security investigation, or written agreement requires retention.</p></section>
  <section><h2>Backups and technical records</h2><p>Deleted information may remain temporarily in encrypted backups until those backups are overwritten under normal rotation. Backup data is isolated from ordinary product access and retained only for continuity, security, or legal obligations. Security and audit records may be retained longer when needed to investigate access, protect the service, or demonstrate compliance.</p></section>
  <section><h2>Financial and legal records</h2><p>Invoices, transaction records, contracts, consent records, and required business records may be retained for the period required by tax, accounting, contract, and other law. These records are not used to restore deleted clinical content.</p></section>
  <section><h2>Requests</h2><p>An authorized account owner may request export, correction, or deletion through the product or at <a href={PRIVACY_EMAIL_HREF}>{PRIVACY_EMAIL}</a>. We verify identity and authority before acting and will acknowledge the request with the applicable scope and timeline. A client should generally direct requests to their healthcare practice, which controls the record.</p></section>
  </PublicPolicyPage> }
